<a href="https://colab.research.google.com/github/ehtesam75/Machine-learning-notes/blob/main/Pandas/Pandas_basic_ipynab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### importing pandas

In [ ]:
import numpy as np
import pandas as pd

### series from list

In [ ]:
#series
country = ['india', 'pakistan', 'bangladesh']
pd.Series(country)
#Series is a class and country is sent as object
#dtype: object: every element dtype is objects. in most case, panda identify string as object

0         india
1      pakistan
2    bangladesh
dtype: object

In [ ]:
#integer
runs = [100, 200, 300]
pd.Series(runs)

0    100
1    200
2    300
dtype: int64

### custom index

In [ ]:
marks = [56, 77, 92]
subjects = ['maths', 'science', 'english']
pd.Series(marks, index = subjects)
pd.Series(marks, subjects) #same but shorter

maths      56
science    77
english    92
dtype: int64

### setting a name

In [ ]:
pd.Series(marks, index = subjects, name = 'makrs of ehtesam')

maths      56
science    77
english    92
Name: makrs of ehtesam, dtype: int64